name: AI Code Review

on:
  issue_comment:
    types: [created]

permissions: write-all

jobs:
  ai-review:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Run AI Reviewer
        uses: visionworksai/ai-code-reviewer@main
        with:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
          INPUT_EXCLUDE: "*.md, docs/**"
